language: c
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
script:
  - asdf plugin-add vals ./
  - asdf list-all vals
  - asdf plugin-test vals ./ 'vals --version'
